    <footer class="section">
      <div class="section-content footer-content">
        <?php /* print render($page['footer']); */ ?>

        <div class="region region-footer">
          <h2>Stay Connected to Pressflow</h2>
          <div id="footer-left-col" class="footer-col social">
            <div class="footer-social-btn"><i class="icon-twitter icon-large"></i><a href="http://twitter.com/#!/Pressflow" target="_blank" title="Pressflow on Twitter" > Twitter</a></div>
            <div class="footer-social-btn"><i class="icon-facebook icon-large"></i><a href="http://facebook.com/Pressflow" target="_blank" title="Pressflow on Facebook"> Facebook</a></div>
            <div class="footer-social-btn"><i class="icon-google-plus icon-large"></i><a href="https://plus.google.com/u/0/110017415213242121438" target="_blank" title="Pressflow on Google+"> Google+</a></div>
          </div>

          <div id="footer-right-col" class="footer-col">
            <!-- Begin MailChimp Signup Form -->
            <div id="mc_embed_signup">
              <form action="http://fourkitchens.us2.list-manage.com/subscribe/post?u=a69fca90d904cf3933c9776c3&amp;id=823153bfef" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank">
                <input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL" placeholder="Get the newsletter">
                <input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button">
                <div id="mce-responses" class="clear">
                  <div class="response" id="mce-error-response" style="display:none"></div>
                  <div class="response" id="mce-success-response" style="display:none"></div>
                </div>
              </form>
            </div>
            <!--End mc_embed_signup-->
          </div>
          <div class="footer-foot">
            Pressflow is a registered trademark of <a href="http://fourkitchens.com">Four Kitchens</a>, home of <a href="http://fourkitchens.com/team/">The Web Chefs</a>.<br>
            All content, except where noted otherwise, is copyright 2016 Four Kitchens and is licensed under the <a href="http://creativecommons.org/licenses/by-sa/3.0/" target="_blank">Creative Commons Attribution-ShareAlike 3.0 license</a>.<br>
            A product of <a href="http://twitter.com/davidstrauss">David Strauss</a>, Four Kitchens, and friends.
          </div>
        </div><!-- .region-footer -->

      </div>
    </footer>
