    <footer class="section">
      <div class="section-content footer-content">
        <?php /* print render($page['footer']); */ ?>

        <div class="region region-footer">
          <h2>Stay Connected to Pressflow</h2>
          <div id="footer-left-col" class="footer-col social">
            <a class="icon-twitter-sign" href="http://twitter.com/#!/Pressflow" target="_blank" title="Pressflow on Twitter" > Twitter</a>
            <a class="icon-facebook-sign" href="http://facebook.com/Pressflow" target="_blank" title="Pressflow on Facebook"> Facebook</a>
            <a class="icon-google-plus" href="https://plus.google.com/u/0/110017415213242121438" target="_blank" title="Pressflow on Google+">Google+</a>
          </div>

          <div id="footer-right-col" class="footer-col">
            <!-- Begin MailChimp Signup Form -->
            <div id="mc_embed_signup">
              <form action="http://fourkitchens.us2.list-manage.com/subscribe/post?u=a69fca90d904cf3933c9776c3&amp;id=823153bfef" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank">
                <input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
                <input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button">
                <div id="mce-responses" class="clear">
                  <div class="response" id="mce-error-response" style="display:none"></div>
                  <div class="response" id="mce-success-response" style="display:none"></div>
                </div>
              </form>
            </div>
            <!--End mc_embed_signup-->
          </div>
          <div class="footer-foot">&copy; Pressflow is a trademark of Four Kitchens, home of the web chefs.</div>
        </div><!-- .region-footer -->

      </div>
    </footer>
